### ISSUE TITLE
Support default AWS credentials providers

### ISSUE THREAD

**Issue by timmattison** [amirzed/provisionpad#4]
Is it possible to update this tool to use the default AWS credentials providers mechanisms? This is all supported natively by boto3.

I may have missed it but the first time I ran it it asked for credentials.

**Comment by amirzed** [comment]
Yes, I see your point. What you are saying should improve `propad initiate`. When you run `propad initiate` it asks for credentials and stores them in `~/.provisionpad/env_variable.json` and later it just uses them.

It will need some extra code in  `propad initiate`  to check for the credentials first rather than explicitely asking for them.
